# Makefile of MyThread

include $(PROJ_ROOT)/IncludePre.mk

LIB_NAME = MyThread
LIB_SRCS = MyMutex.c MySemaphore.c MyThread.c
TARGET_SRCS = TestMutex.c TestSemaphore.c TestThread.c 

# 의존성 규칙에 포함시킬 라이브러리입니다.
DEPEND_LIBS = 

# 외부 시스템 라이브러리입니다.
LIBS += -lpthread

include $(PROJ_ROOT)/IncludePost.mk
